services:

  nmap_exporter:
    container_name: nmap_exporter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    environment:
#      - DEBUG=true
    ports:
      - "9292:9292"
    stdin_open: true
    tty: true
