services:

  nmap_exporter:
    container_name: nmap_exporter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
#      - DEBUG=true
      - NMAP_DEFAULT_SCAN_HOST=10.0.1.0/24
    ports:
      - "9292:9292"
    stdin_open: true
    tty: true
